### ISSUE TITLE
Instruction for compilation

### ISSUE THREAD

**Issue by jmQZekdEEDskzSl74iL2eQT5bLiRcdka** [PigeonMC/Pukkit#1]
Hello,
I'm having a trouble figuring out how to compile this project and what source I am probably missing.

**Comment by phase** [comment]
It uses Gradle. You can import it into IntelliJ using `Import Gradle Project`, or run `./gradlew build`.

This project isn't being maintained right now, but I do plan to do this _eventually_. This is essentially the original Bukkit 1.7.3, but using the Gradle build system.

**Comment by jmQZekdEEDskzSl74iL2eQT5bLiRcdka** [comment]
But how do I get gradle to make bukkit.jar, I'm only getting a bunch of org.bukkit classes in my out directory.
